# Generated by Django 6.1.1 on 2026-09-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmanager',
            old_name='status',
            new_name='completed',
        ),
    ]
